apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-test-client-svc
spec:
  selector:
    app: {{ .Release.Name }}-test-client
  ports:
    - name: {{ .Release.Name }}-test-client
      protocol: {{ .Values.testClient.service.protocol }}
      port: {{ .Values.testClient.service.port }}
      targetPort: {{ .Values.testClient.service.port }}