apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client-svc
spec:
  selector:
    app: {{ .Release.Name }}-client
  ports:
    - name: {{ .Release.Name }}-client
      protocol: {{ .Values.hsClient.service.protocol }}
      port: {{ .Values.hsClient.service.port }}
      targetPort: {{ .Values.hsClient.service.port }}