apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server-svc
spec:
  selector:
    app: {{ .Release.Name }}-server
    monitoring: "enabled"
  ports:
    - name: {{ .Release.Name }}-server
      protocol: {{ .Values.server.service.protocol }}
      port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.port }}