# Default values for hs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

hsClient:
  image:
    name: "kaburi/hs-client"
    version: "86"
  service:
    protocol: TCP
    port: 3020
  resources:
    limits:
      memory: "256Mi"    # 메모리 제한
      cpu: "500m"        # CPU 제한
    requests:
      memory: "128Mi"    # 최소 메모리 요청
      cpu: "250m"

hsServer:
  image:
    name: "kaburi/hs-server"
    version: "81"
  service:
    protocol: TCP
    port: 4020
  resources:
    limits:
      memory: "256Mi"    # 메모리 제한
      cpu: "500m"        # CPU 제한
    requests:
      memory: "128Mi"    # 최소 메모리 요청
      cpu: "250m"

ingress:
  name: hs-ingress
  enabled: true
  className: "nginx"
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/hsts: 'true'
  hosts:
  - host: hs.click-soft.co.kr     
    paths:
    - path: /?(.*)
      pathType: ImplementationSpecific
      backend:
        service:
          name: hs-client-svc
          port:
            number: 3020
    - path: /api/?(.*)
      pathType: ImplementationSpecific
      backend:
        service:
          name: hs-server-svc
          port:
            number: 4020
  tls: []
  
service:
  port: 80
