apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elastic-data-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/data/elasticsearch-data-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elastic-data-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/data/elasticsearch-data-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elastic-master-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/data/elasticsearch-master-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elastic-master-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/data/elasticsearch-master-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elastic
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/data/es