apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server-depl
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
    spec:
      containers:
      - name: {{ .Release.Name }}-server
        image: "{{ .Values.server.image.name }}:{{ .Values.server.image.version }}"
        {{- if .Values.client.resources }}
        resources:
          limits:
            memory: {{ .Values.client.resources.limits.memory | default "256Mi" }}    # 메모리 제한
            cpu: {{ .Values.client.resources.limits.cpu | default "500m" }}           # CPU 제한
          requests:
            memory: {{ .Values.client.resources.requests.memory | default "128Mi" }}  # 최소 메모리 요청
            cpu: {{ .Values.client.resources.requests.cpu | default "250m" }}         # 최소 CPU 요청
        {{- else }}
        resources:
          limits:
            memory: "256Mi"    # 메모리 제한
            cpu: "500m"        # CPU 제한
          requests:
            memory: "128Mi"    # 최소 메모리 요청
            cpu: "250m"        # 최소 CPU 요청
        {{- end }}
        env:
        - name: CLICK_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: click-log-secr
              key: click_database_url
        - name: COLLECT_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: click-log-secr
              key: collect_database_url
        - name: CPM_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: click-log-secr
              key: cpm_database_url
        - name: NODE_ENV
          value: production
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: click-log-secr
              key: jwt_key
        - name: USER_ID
          valueFrom:
            secretKeyRef:
              name: click-log-secr
              key: user_id
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: click-log-secr
              key: password
        - name: CLICK_HEADER_KEY
          valueFrom:
            secretKeyRef:
              name: click-log-secr
              key: click_header_key
        - name: CLICK_HEADER_VALUE
          valueFrom:
            secretKeyRef:
              name: click-log-secr
              key: click_header_value
        - name: SMS_DATABASE_CONFIG
          valueFrom:
            secretKeyRef:
              name: click-log-secr
              key: sms_database_config
        - name: SMS_ID
          valueFrom:
            secretKeyRef:
              name: click-log-secr
              key: sms_id
        - name: SMS_CALLBACK
          valueFrom:
            secretKeyRef:
              name: click-log-secr
              key: sms_callback
