apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server-depl
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
    spec:
      containers:
      - name: {{ .Release.Name }}-server
        image: "{{ .Values.server.image.name }}:{{ .Values.server.image.version }}"
        env:
        - name: CLICK_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: click-log-secr
              key: click_database_url
        - name: CPM_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: click-log-secr
              key: cpm_database_url
        - name: NODE_ENV
          value: production
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: click-log-secr
              key: jwt_key
        - name: USER_ID
          valueFrom:
            secretKeyRef:
              name: click-log-secr
              key: user_id
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: click-log-secr
              key: password
        - name: CLICK_HEADER_KEY
          valueFrom:
            secretKeyRef:
              name: click-log-secr
              key: click_header_key
        - name: CLICK_HEADER_VALUE
          valueFrom:
            secretKeyRef:
              name: click-log-secr
              key: click_header_value