replicaCount: 1

client:
  image:
    name: "kaburi/click-log-client"
    version: "9"
  service:
    protocol: TCP
    port: 80

server:
  image:
    name: "kaburi/click-log-server"
    version: "81"
  service:
    protocol: TCP
    port: 3000

ingress:
  name: click-log-ingress
  enabled: true
  className: "nginx"
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/hsts: 'true'
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
  hosts:
  - host: log.click-soft.co.kr     
    paths:
    - path: /?(.*)
      pathType: ImplementationSpecific
      backend:
        service:
          name: click-log-client-svc
          port:
            number: 80
    - path: /api/?(.*)
      pathType: ImplementationSpecific
      backend:
        service:
          name: click-log-server-svc
          port:
            number: 3000
  tls: []
  
service:
  port: 80