# Default values for hs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

client:
  image:
    name: "kaburi/click-store"
    version: "140"
  service:
    protocol: TCP
    port: 3000

testClient:
  image:
    name: "kaburi/click-store"
    version: "140"
  service:
    protocol: TCP
    port: 3000

server:
  image:
    name: "kaburi/click-store-server"
    version: "2"
  service:
    protocol: TCP
    port: 4000

ingress:
  name: click-store-ingress
  enabled: true
  className: "nginx"
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/hsts: 'true'
  hosts:
  - host: www.click-soft.shop
    paths:
    - path: /?(.*)
      pathType: ImplementationSpecific
      backend:
        service:
          name: click-store-client-svc
          port:
            number: 3000
  - host: test.click-soft.shop
    paths:
    - path: /?(.*)
      pathType: ImplementationSpecific
      backend:
        service:
          name: click-store-test-client-svc
          port:
            number: 3000
  - host: api.click-soft.shop
    paths:
    - path: /?(.*)
      pathType: ImplementationSpecific
      backend:
        service:
          name: click-store-server-svc
          port:
            number: 4000
  tls: []
  
service:
  port: 80