apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server-svc
spec:
  selector:
    app: {{ .Release.Name }}-server
  ports:
    - name: {{ .Release.Name }}-server
      protocol: {{ .Values.server.service.protocol }}
      port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.port }}
    - name: {{ .Release.Name }}-grpc
      protocol: TCP
      port: {{ .Values.server.service.grpcPort }}
      targetPort: {{ .Values.server.service.grpcPort }}
