# Default values for hs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

client:
  image:
    name: "kaburi/click-app-client"
    version: "82"
  service:
    protocol: TCP
    port: 80
  resources:
    limits:
      memory: "256Mi"    # 메모리 제한
      cpu: "500m"        # CPU 제한
    requests:
      memory: "128Mi"    # 최소 메모리 요청
      cpu: "250m"
      
server:
  image:
    name: "kaburi/click-app-server"
    version: "23"
  service:
    protocol: TCP
    port: 3000
    grpcPort: 5000
  resources:
    limits:
      memory: "256Mi"    # 메모리 제한
      cpu: "500m"        # CPU 제한
    requests:
      memory: "128Mi"    # 최소 메모리 요청
      cpu: "250m"

ingress:
  name: click-app-ingress
  enabled: true
  className: "nginx"
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/hsts: 'true'
  hosts:
  - host: app.click-soft.co.kr     
    paths:
    - path: /?(.*)
      pathType: ImplementationSpecific
      backend:
        service:
          name: click-app-client-svc
          port:
            number: 80
    - path: /api/?(.*)
      pathType: ImplementationSpecific
      backend:
        service:
          name: click-app-server-svc
          port:
            number: 3000
    # - path: /api/?(.*)
    #   pathType: ImplementationSpecific
    #   backend:
    #     service:
    #       name: click-app-client-svc
    #       port:
    #         number: 3010
  tls: []
  
service:
  port: 80
