# Default values for hs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

client:
  image:
    name: "kaburi/click-sign-client"
    version: "7"
  service:
    protocol: TCP
    port: 3001

server:
  image:
    name: "kaburi/click-sign-server"
    version: "11"
  service:
    protocol: TCP
    port: 4001

ingress:
  name: click-sign-ingress
  enabled: true
  className: "nginx"
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/hsts: 'true'
  hosts:
  - host: sign.click-soft.co.kr     
    paths:
    - path: /?(.*)
      pathType: ImplementationSpecific
      backend:
        service:
          name: click-sign-client-svc
          port:
            number: 3001
  - host: sock.click-soft.co.kr     
    paths:
    - path: /?(.*)
      pathType: ImplementationSpecific
      backend:
        service:
          name: click-sign-server-svc
          port:
            number: 4001
  tls: []
  
service:
  port: 80
