# Default values for hs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

client:
  image:
    name: "kaburi/click-sign-client"
    version: "13"
  service:
    protocol: TCP
    port: 3001
  resources:
    limits:
      memory: "256Mi"    # 메모리 제한
      cpu: "500m"        # CPU 제한
    requests:
      memory: "128Mi"    # 최소 메모리 요청
      cpu: "250m"
      
server:
  image:
    name: "kaburi/click-sign-server"
    version: "16"
  service:
    protocol: TCP
    port: 4001
  resources:
    limits:
      memory: "256Mi"    # 메모리 제한
      cpu: "500m"        # CPU 제한
    requests:
      memory: "128Mi"    # 최소 메모리 요청
      cpu: "250m"
      
ingress:
  name: click-sign-ingress
  enabled: true
  className: "nginx"
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/hsts: 'true'
  hosts:
  - host: sign.click-soft.co.kr     
    paths:
    - path: /?(.*)
      pathType: ImplementationSpecific
      backend:
        service:
          name: click-sign-client-svc
          port:
            number: 3001
  - host: sock.click-soft.co.kr     
    paths:
    - path: /?(.*)
      pathType: ImplementationSpecific
      backend:
        service:
          name: click-sign-server-svc
          port:
            number: 4001
  tls: []
  
service:
  port: 80
